### ISSUE TITLE
No Roswell script despite the README?

### ISSUE THREAD

**Issue by vindarel** [hyotang666/trivial-formatter#3]
Hello,

The README recommends to use Roswell:

    $ ros install hyotang666/trivial-formatter

but…

```
[3/3] Attempting to install the scripts in roswell/ subdirectory of the system...
No roswell scripts found.
```

and there is no roswell script in the sources?

Best,

**Comment by hyotang666** [comment]
Thank you for the suggestion.
But I do not intend to support ROS script now for some reason.

* Trivial-formatter is a very personal project.

IMHO, the question 'Which format is the best format?' is a kind of flavor.
I do not want to fight against a discussion about formatting.

So I want to keep TF as a hermit project.

Quicklisp announces the added libraries when every update.
And such announcements are shared via e.g. [lisp planet](https://planet.lisp.org/).

Roswell does not do such things.
So I choose roswell as installer rather than quicklisp.
Not for ROS scripting feature.

* Trivial-formatter is improved by dogfooding.

I do not want to add features that I do not use.
You know adding is easy but maintenance is hard.

**Comment by vindarel** [comment]
OK, I understand. However, what I don't understand is that your README says we can install TF with Roswell like this:

```
To install trivial-formatter, roswell is recommended.

$ ros install hyotang666/trivial-formatter
```

but it doesn't work… or does it?

The output is:

```
[1/3] System 'trivial-formatter' found. Loading the system..
[2/3] Processing build-hook..
[3/3] Attempting to install the scripts in roswell/ subdirectory of the system...
No roswell scripts found.
```

so step 1 works but there is nothing to complete point 3. 

I was expecting that the Roswell command would install a script and an executable in my path, but since you say

> Roswell does not do such things. So I choose roswell as installer rather than quicklisp. Not for ROS scripting feature.

I now understand nothing is expected to happen at step 3.

Alright! It could be useful but OK.

thanks
